Q1) State differences between Numpy Array and lists. 

Data Type Consistency:

NumPy arrays are homogeneous; they store elements of the same data type, which allows for more efficient storage and operations.
Python lists are heterogeneous; they can store elements of different data types, making them more flexible but potentially less efficient for numerical operatio

ns.
Memory Efficiecy:

NumPy arrays are more memory efficient compared to Python lists, especially for large datasets, because they store data in contiguous memory blocks.
Python lists store references to objects, which consumes more memory and leads to less efficient memory

 usage.
Perfrmance:

NumPy arrays offer faster numerical computations and operations compared to Python lists, especially for large datasets, due to their fixed data type and contiguous memory layout.
Python lists are slower for numerical computations because they are dynamically typed and store references 

to objects.
Convenience ofOperations:

NumPy arrays provide a wide range of mathematical functions and operations optimized for numerical computations, such as element-wise operations, linear algebra, Fourier transforms, and random number generation.
Python lists offer fewer mathematical functions and operations compared to NumPy arrays and are generally less optimized for numerica

l computations.
Sntax and Usage:

NumPy arrays have a more concise and powerful syntax for array operations and manipulations, including slicing, indexing, reshaping, and broadcasting.
Python lists have a simpler syntax for basic operations but lack the advanced functionality and convenience provid
ed by NumPy arrays.
Sze and Flexibility:

NumPy arrays have a fixed size once created, and their size cannot be changed dynamically (though you can create new arrays with different sizes).
Python lists are dynamic and can grow or shrink dynamically as elements are added or removed.

Q2) Write a Code to create 50 evenly spaced numbers between 0 to 10.

In [2]:
import numpy as np 

random_numbers=np.linspace(0,10,50)
print(random_numbers)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


Q3) Write a Code to create an array of shape (4,5) with random samples
with random seed 7. 

In [8]:
#seed method we are using to fix the random number to be genrated

np.random.seed(7)

arr=np.random.rand(4,5)
print(arr)

[[0.07630829 0.77991879 0.43840923 0.72346518 0.97798951]
 [0.53849587 0.50112046 0.07205113 0.26843898 0.4998825 ]
 [0.67923    0.80373904 0.38094113 0.06593635 0.2881456 ]
 [0.90959353 0.21338535 0.45212396 0.93120602 0.02489923]]


Q4) Write a Code to reshape the array created in Q3 into shape (2,10).

In [10]:
new_arr=arr.reshape(2,10)
print(new_arr)

[[0.07630829 0.77991879 0.43840923 0.72346518 0.97798951 0.53849587
  0.50112046 0.07205113 0.26843898 0.4998825 ]
 [0.67923    0.80373904 0.38094113 0.06593635 0.2881456  0.90959353
  0.21338535 0.45212396 0.93120602 0.02489923]]


Q5) Create a 1D array starting from 0 ending with 100 with step size 10 and
another array starting from 1000 ending with 10000 with step size 1000 and
then concatenate two arrays created.

In [39]:
arr_1=np.arange(0,100,10)
arr_2=np.arange(1000,10000,1000)
arr_conn=np.concatenate([arr_1,arr_2])
print(arr_1)
print(arr_2)
print(arr_conn)


[ 0 10 20 30 40 50 60 70 80 90]
[1000 2000 3000 4000 5000 6000 7000 8000 9000]
[   0   10   20   30   40   50   60   70   80   90 1000 2000 3000 4000
 5000 6000 7000 8000 9000]
<class 'numpy.ndarray'>


Q6)  Use the array created in Q5 and replace the values less than 50 as
<50. 

In [42]:
np.where(arr_conn<50,'<50',arr_conn)

array(['<50', '<50', '<50', '<50', '<50', '50', '60', '70', '80', '90',
       '1000', '2000', '3000', '4000', '5000', '6000', '7000', '8000',
       '9000'], dtype='<U11')

Q7) Write a Code to create 1D, 2D, and 3D arrays randomly

In [46]:
arr_1d=np.arange(1,10)
arr_2d=np.random.rand(4,5)
arr_3d=np.random.rand(3,3,3)

print("1D array",arr_1d)
print("\n\n\n")
print("2D array",arr_2d)
print("\n\n\n")
print("3D array",arr_3d)



1D array [1 2 3 4 5 6 7 8 9]




2D array [[0.78673059 0.64078106 0.49601706 0.47305581 0.47423469]
 [0.9435772  0.73779928 0.041573   0.75778036 0.513401  ]
 [0.17842575 0.39200156 0.93959276 0.21291858 0.81329627]
 [0.40364858 0.58672092 0.18599889 0.81232251 0.58084741]]




3D array [[[0.44693254 0.79808141 0.54427185]
  [0.41841659 0.01915666 0.68377373]
  [0.48809792 0.22057967 0.55054305]]

 [[0.52259111 0.48755248 0.26303148]
  [0.52728579 0.98446573 0.62342345]
  [0.62955693 0.9099729  0.96251949]]

 [[0.5850998  0.16489774 0.39159332]
  [0.94455493 0.34339118 0.70507037]
  [0.4628868  0.38679069 0.52843256]]]


Q8) Write a Code to create an array with 10 random integers within 100

In [47]:
arr=np.linspace(0,100,10)
print(arr)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


Q9) Create an array with sample data with a shape of (5,4) with standard
normal distribution with the random seed of 201. 

In [49]:
np.random.seed(201)
arr9=np.random.rand(5,4)
print(arr)


[[0.1139046  0.74788082 0.6110594  0.8096918 ]
 [0.71285749 0.14003681 0.26751188 0.14760445]
 [0.22806792 0.23556173 0.69002382 0.14834782]
 [0.44560583 0.70084254 0.09663865 0.88263259]
 [0.86983229 0.84459421 0.27370208 0.78567954]]


Q10) Use the array from Q9 and create a Dataframe with
index=['L','M','N','O','P'], columns=['A','B','C','D'] 

In [51]:
import pandas as pd

df=pd.DataFrame(arr9,index=['L','M','N','O','P'], columns=['A','B','C','D'])
df.head()
#print(df)

A         B         C         D
L  0.113905  0.747881  0.611059  0.809692
M  0.712857  0.140037  0.267512  0.147604
N  0.228068  0.235562  0.690024  0.148348
O  0.445606  0.700843  0.096639  0.882633
P  0.869832  0.844594  0.273702  0.785680

Q11) Find the most frequent value in an numpy 1D array. Use array x =
np.array([10,20,66,20,10,30,50,60,70,60,66,12,13,66]).

In [55]:
arr_1=np.array([10,20,66,20,10,30,50,60,70,60,66,12,13,66])
np.argmax(np.bincount(arr_1))


66

Q11) Find the most frequent value in an numpy 1D array. Use array x =
np.array([10,20,66,20,10,30,50,60,70,60,66,12,13,66])

In [57]:
arr11=np.array([10,20,66,20,10,30,50,60,70,60,66,12,13,66])
arr11.flatten()

array([10, 20, 66, 20, 10, 30, 50, 60, 70, 60, 66, 12, 13, 66])